version: "3"
services:
  go:
    build: .
    image: golang:1.11.5
    volumes:
      - .:/go/src/github.com/cosma/pluto
    working_dir: /go/src/github.com/cosma/pluto
    command: /go/bin/gin run main.go
    environment:
      PORT: 3000
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - 2345:2345
      - 3000:3000
